# Generated by Django 5.0 on 2023-12-13 04:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_msg_mailing_mailing_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='clients',
            new_name='client',
        ),
        migrations.AlterField(
            model_name='logfile',
            name='status_log',
            field=models.BooleanField(choices=[('SENT', 'Отправлено'), ('FAILED', 'Не удалось отправить')], default='SENT', verbose_name='статус попытки'),
        ),
        migrations.AlterField(
            model_name='logfile',
            name='time_log',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата и время последней попытки'),
        ),
    ]
