# Generated by Django 4.2.7 on 2023-12-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_client_user_mailing_user_msg_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='is_activated',
            field=models.BooleanField(default=True, verbose_name='действующая'),
        ),
    ]
